-- BUOI03BT01
SELECT NAME FROM CITY
WHERE POPULATION > 120000
AND COUNTRYCODE = "USA" 
-- BUOI03BT02
SELECT * 
FROM CITY
WHERE COUNTRYCODE = 'JPN'
-- BUOI03BT03
SELECT CITY, STATE FROM STATION
--BUOI03BT04
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE 'A%'OR CITY LIKE 'E%'OR CITY LIKE 'I%'OR CITY LIKE 'O%'OR CITY LIKE 'U%')
--BUOI03BT05
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE '%A'OR CITY LIKE '%E'OR CITY LIKE '%I'OR CITY LIKE '%O'OR CITY LIKE '%U')
--BUOI03BT06
SELECT DISTINCT CITY FROM STATION
WHERE NOT (CITY LIKE 'A%'OR CITY LIKE 'E%'OR CITY LIKE 'I%'OR CITY LIKE 'O%'OR CITY LIKE 'U%')
--BUOI03BT07
SELECT NAME FROM EMPLOYEE
ORDER BY NAME 
--BUOI03BT08
SELECT NAME FROM EMPLOYEE
WHERE SALARY > 2000 AND MONTHS <10
--BUOI03BT09
SELECT product_id FROM Products
WHERE low_fats = 'Y' AND recyclable = 'Y'
--BUOI03BT10
SELECT NAME FROM Customer
WHERE referee_id <> 2 OR referee_id IS NULL
--BUOI03BT11
SELECT name, population, area FROM world 
WHERE area > 3000000 OR population >= 25000000
--BUOI03BT12
SELECT DISTINCT author_id AS ID FROM Views
WHERE viewer_id = author_id
ORDER BY author_id ASC
--BUOI03BT13
SELECT part, assembly_step FROM parts_assembly
WHERE finish_date IS NULL
--BUOI03BT14
select * from lyft_drivers
WHERE yearly_salary <= 30000 OR yearly_salary >= 70000 
--BUOI03BT15
SELECT advertising_channel FROM uber_advertising
WHERE money_spent > 100000 AND year = 2019
